### ISSUE TITLE
android docs no work

### ISSUE THREAD

**Issue by Unihedro** [mangstadt/OakBot#24]
http://chat.stackoverflow.com/transcript/message/26156875#26156875

leads to 404 page

**Comment by mangstadt** [comment]
There doesn't appear to be a "NonNull" annotation in the "android.annotation" package. o_O

http://developer.android.com/reference/android/annotation/package-summary.html

Looks like it's in the "android.support.annotation" package.

http://developer.android.com/reference/android/support/annotation/NonNull.html

**Comment by mangstadt** [comment]
And dang it @Uni, don't yell at me!!!

**Comment by mangstadt** [comment]
I built the Javadocs for the **real** Android Java SDK by downloading the source code from Android's package manager.  However, the source code still contains the `android.annotation.NonNull` class, even though it does not exist in the online reference documentation.
